heat_template_version: 2013-05-23

description: >
  Deploying python on 1 machine

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: cloud-pyserver
  flavor:
    type: string
    description: Flavor used for server
    default: INF4410-mini

  image:
    type: string
    description: Image used for server
    default: INF4410-Ubuntu-trusty-mini
    
  network_id:
    type: string
    description: ID of network used
    default: 938775f1-1d27-4d35-a41d-e76eac6797db
    
  server_url:
    type: string
    description: Github link to python server code
    default: https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
    

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: network_id }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            curl server_url -o server.py -s;
            python server.py;
          params:
            server_url: { get_param: server_url }
            
  floating_ip:
    type: OS::Nova::FloatingIP
    properties:
      pool: ext-net
       
  association:
    type: OS::Nova::FloatingIPAssociation
    properties:
      floating_ip: {get_resource: floating_ip}
      server_id: {get_resource: server}
     

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }

